### ISSUE TITLE
cell cycle scoring may need updates

### ISSUE THREAD

**Issue by hwick** [hbctraining/scRNA-seq_online#107]
The resources on [cell cycle scoring](https://hbctraining.github.io/scRNA-seq_online/lessons/cell_cycle_scoring.html) might need some updating 
-consider adding required libraries (rCurl, AnnotationHub, ensembldb)
-object seurat_control doesn't appear in materials linking to the page (page is currently linked from [06_SC_SCT_normalization](https://hbctraining.github.io/scRNA-seq_online/lessons/06_SC_SCT_normalization.html)
-skips normalization step which appears on the SC_SCT_normalization page
-RunPCA step throws an error (consider adding FindVariableFeatures step which is mentioned on the SC_SCT_normalization page):
```
Error in PrepDR(object = object, features = features, verbose = verbose) : 
Variable features haven't been set. Run FindVariableFeatures() or provide a vector of feature names.

**Comment by hwick** [comment]
I have added the libraries and changed seurat_control to seurat_phase, but ended up not adding the normalization step since it mentions "PCA is run only using the most variable features identified previously."

**Comment by mistrm82** [comment]
thanks @hwick ! I ended up adding FindVariableFeatures() and just a note to not run it if you had previously. I think we're all set here!
