### ISSUE TITLE
cell cycle phase in seurat_integrated isn't kept?

### ISSUE THREAD

**Issue by hwick** [hbctraining/scRNA-seq_online#108]
Going through the materials, I successfully added cell cycle phase to seurat_norm
However, SCT transform does not seem to keep phase in seurat_integrated

**Comment by mistrm82** [comment]
Double checked seurat_phase, individual components of seurat_split (after SCT) and seurat_integrated  - all have phase information. Maybe we can check your dataset together @hwick 

closing issue since it does not affect class materials
