### ISSUE TITLE
Quality Control visualizations

### ISSUE THREAD

**Issue by chenqing1991** [hbctraining/scRNA-seq_online#110]
Hi，I have just learned  the scRNA-seq_online course，I  have a question 

when you visualiza the UMI counts (transcripts) per cell by code as bellow:
# Visualize the number UMIs/transcripts per cell
metadata %>% 
  	ggplot(aes(color=sample, x=nUMI, fill= sample)) + 
  	geom_density(alpha = 0.2) + 
  	scale_x_log10() + 
  	theme_classic() +
  	ylab("Cell density") +
  	geom_vline(xintercept = 500)

I'm wonder should  the xintercept parameter changed by log10( )?  Just as this : +geom_vline(xintercept = log10(500))

Thanks very much!

**Comment by mistrm82** [comment]
Hi @chenqing1991 ,

It doesn't have to be on a log scale, but if you do then the differences are more emphasized
