### ISSUE TITLE
cycle.rda file missing

### ISSUE THREAD

**Issue by ChrisSteel-bio** [hbctraining/scRNA-seq_online#115]
I'm working my way through lesson 6. I can't seem to find the Rdata file "cycle.rda" in the repo. I am looking in the wrong place?

Cheers,
Chris

**Comment by mistrm82** [comment]
Hi @ChrisSteel-bio 
cycle.rda is located in the project folder you download at the beginning of the workshop. You can find this at the top of our schedule page, but also[ linked here](https://www.dropbox.com/s/vop78wq76h02a2f/single_cell_rnaseq.zip?dl=1)
