### ISSUE TITLE
Trouble downloading ' scRNA-seq filtered counts' from the Pseudobulk DEG analysis tutorial 

### ISSUE THREAD

**Issue by yeseul830** [hbctraining/scRNA-seq_online#118]
Hello, 

I am trying to go over downstream analysis following [pseudobulk DEG analysis tutorial page](https://hbctraining.github.io/scRNA-seq_online/lessons/pseudobulk_DESeq2_scrnaseq.html), and have trouble downloading the 'scRNA-seq filtered counts' data with the right click.
May I ask some help with this issue?

Thank you, 
Yeseul

**Comment by ronfinn** [comment]
Has this been resolved? I also still cannot download this data

**Comment by yeseul830** [comment]
Hello, can I get an update on this issue?

**Comment by mistrm82** [comment]
Hi, I'm sorry we had trouble locating the file as there has been some reorg in our group. Please try [this link](https://www.dropbox.com/scl/fi/1y24rh3ybkkkbzt7lcj8k/scRNA-seq_pseudobulk_filtered_sce.rds?rlkey=e8vnlietbwvefyunv0ynv1l5s&dl=1) and let us know if it works out.

We are planning on testing it as well, but also working on a more detailed workshop for pseudobulk DE

Although
