### ISSUE TITLE
Default assay to use for finding marker

### ISSUE THREAD

**Issue by jihe-liu** [hbctraining/scRNA-seq_online#14]
Based on these two threads: https://github.com/satijalab/seurat/issues/1501, https://github.com/satijalab/seurat/issues/1836, one could use sctransform data to perform marker identification, or the normalized and scaled data. The note in our current material says "the functions for finding markers will automatically pull the raw counts".

**Comment by mistrm82** [comment]
@jihe-liu  will be adding `DefaultAssay(seurat_integrated) <- "SCT"`, running through code and updating images/results where necessary

**Comment by jihe-liu** [comment]
Currently, our lesson used normalized count for finding markers, which is also a correct way. The text explanation for this part has been revised accordingly. The output of `DefaultAssay(seurat_integrated) <- "SCT"` is largely the same as our current lesson, except that the scale for featurePlot changes a bit.

**Comment by mistrm82** [comment]
done
