### ISSUE TITLE
Some warnings to look over (from student)

### ISSUE THREAD

**Issue by rkhetani** [hbctraining/scRNA-seq_online#15]
I have two warning messages although I could succeeded in following the homework.

-For “Clustering” part, when I run the following code, a warning message popped up.
Even though I found this message, I succeeded in the following tasks.
DimPlot(seurat_integrated,
+         reduction = "umap",
+         label = TRUE,
+         label.size = 6)
Warning message:
Using `as.character()` on a quosure is deprecated as of rlang 0.3.0.
Please use `as_label()` or `as_name()` instead.
This warning is displayed once per session.

-For “Clustering quality control” part, when I run the following code, I found this warning.
As I said earlier, I could see the same result as the textbook.
#Determine metrics to plot present in seurat_integrated@meta.data
> metrics <- c("nUMI", "nGene", "S.Score", "G2M.Score", "mitoRatio")
> FeaturePlot(seurat_integrated,
+             reduction = "umap",
+             features = metrics,
+             pt.size = 0.4,
+             sort.cell = TRUE,
+             min.cutoff = 'q10',
+             label = TRUE)
Warning: The sort.cell parameter is being deprecated. Please use the order parameter instead for equivalent functionality.

**Comment by mistrm82** [comment]
updated all instances of this `sort.cell` argument to `order`. (cluster quality and marker identification lessons)
