### ISSUE TITLE
link to show an example of cell cycle regression

### ISSUE THREAD

**Issue by mistrm82** [hbctraining/scRNA-seq_online#24]
https://satijalab.org/seurat/v3.1/cell_cycle_vignette.html

An example of when you do see an effect

**Comment by marypiper** [comment]
Create note with link and extracting two PCA plots to demonstrate effect

**Comment by rkhetani** [comment]
@mistrm82 I have created a pull request with the changes for this - https://github.com/hbctraining/scRNA-seq_online/pull/29.

**Comment by mistrm82** [comment]
updated code, thanks @rkhetani
