### ISSUE TITLE
incorrect description of avg_logfc in markers lesson

### ISSUE THREAD

**Issue by marypiper** [hbctraining/scRNA-seq_online#27]
From email:
 
I have a query regarding the avg_log fold change mentioned in this link: https://github.com/hbctraining/scRNA-seq_online/blob/master/lessons/09_merged_SC_marker_identification.md
The training materials indicate that this is a log2 fold change.
The link from the Seurat development team suggests that this is natural log fold change (https://github.com/satijalab/seurat/issues/741 )

**Comment by jihe-liu** [comment]
Done.
