### ISSUE TITLE
include the cycle.rda in the project download?

### ISSUE THREAD

**Issue by mistrm82** [hbctraining/scRNA-seq_online#33]
since we are having them download, a suggestion to have everything they need there

**Comment by rkhetani** [comment]
Added cycle.rda to data folder and updated links to project download in prep instructions and the relevant markdowns.

**Comment by imet-k** [comment]
Hi! Thank you for the interesting course. I could not find cycle.rda in the data folder. Can you provide it again? Thanks in advance.
