### ISSUE TITLE
Update to sctransform requires additional package install

### ISSUE THREAD

**Issue by marypiper** [hbctraining/scRNA-seq_online#34]
https://satijalab.org/seurat/articles/sctransform_vignette.html

The latest version of sctransform also supports using glmGamPoi package which substantially improves the speed of the learning procedure. It can be invoked by specifying method="glmGamPoi".

if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")

BiocManager::install("glmGamPoi")
pbmc <- SCTransform(pbmc, method = "glmGamPoi", vars.to.regress = "percent.mt", verbose = FALSE)

**Comment by mistrm82** [comment]
added to install page
