### ISSUE TITLE
Update marker ID to be log2 fc

### ISSUE THREAD

**Issue by marypiper** [hbctraining/scRNA-seq_online#37]
Re: Archana:

In the recent update to Seurat (v4.0.0), the log Fold Change value has been changed to log2 scale.

References: https://github.com/satijalab/seurat/blob/4e868fcde49dc0a3df47f94f5fb54a421bfdf7bc/NEWS.md#changes-1

https://satijalab.org/seurat/reference/findallmarkers

**Comment by jihe-liu** [comment]
Revised.
