### ISSUE TITLE
poll question edits

### ISSUE THREAD

**Issue by mistrm82** [hbctraining/scRNA-seq_online#4]
Clarify the responses and the double negative questions i.e Pick the *NOT* , then nots in the responses -

**Comment by rkhetani** [comment]
@jihe-liu and @mistrm82 I have updated some of the phrasing of the Zoom poll questions and marked what I thought were the correct answers.

Please look over to make sure all the correct answers are marked in bold (day 1 and day 2 polls) and if the phrasing is clearer

**Comment by rkhetani** [comment]
done, resolved
