### ISSUE TITLE
Wrong formula or description when calculating log10GenesPerUMI

### ISSUE THREAD

**Issue by michael-kotliar** [hbctraining/scRNA-seq_online#40]
In this file https://github.com/hbctraining/scRNA-seq_online/blob/master/lessons/04_SC_quality_control.md either the description or formula should be corrected, because `log10(x/y) = log10(x) - log10(y)` and not `log10(x/y) = log10(x) / log10(y)`

### Number of genes detected per UMI

This value is quite easy to calculate, as we simply divide the number of genes detected per cell by the number of UMIs per cell. We will log10 transform the result for a better comparison between samples.

```r
# Add number of genes per UMI for each cell to metadata
merged_seurat$log10GenesPerUMI <- log10(merged_seurat$nFeature_RNA) / log10(merged_seurat$nCount_RNA)
```

**Comment by marypiper** [comment]
Thanks @michael-kotliar for bringing this to our attention. @mistrm82, I have fixed the language, but since it is the lesson you normally teach, can you make sure it is clear for you?
