### ISSUE TITLE
suggested QC homework questions

### ISSUE THREAD

**Issue by mistrm82** [hbctraining/scRNA-seq_online#48]
Perform all of the same plots using the filtered data as we had done with the unfiltered data and answer the following questions:

* Report the number of cells left for each sample.
* Did we lose a lot of cells per sample? If the cell numbers remaining are much lower than the number of cells we loaded, how can we explain this loss?

* After filtering for nGene per cell, you should still observe a small shoulder to the right of the main peak. What might this shoulder represent?

_Question for us --would this apply to nUMI? what does the shoulder represent in the nUMI plot (i.e if a cell has a lot of transcripts associated, it's sequenced alot)_
 
* The normal range of values for genes detected is ______ to _____. We set a fairly liberal threshold and keep cells that have as few as 250 genes detected. How do we explain cells that have so few genes being detected, considering the large number of genes present in the genome? (_this one could use some work_)

* After filtering, when plotting the nGene against nUMI do you observe any data points in the bottom right quadrant of the plot? If you don't see anything, what can you say about these cells that have been removed?

A good exercise would be to provide a nUMI or nGene plot (from a previous consult?) and ask them to choose the threshold. Explain why you chose the threshold

**Comment by mistrm82** [comment]
I added most, but the two below were not included. If we have time to review/reword together we can add these at a later date:

1. Observed shoulder on nUMI plot-- what does it represent (i.e if a cell has a lot of transcripts associated, it's sequenced alot)

2. The typical range of values for genes can vary for many reasons (i.e ...) We set a fairly liberal threshold and keep cells that have as few as 250 genes detected. How do we explain cells that have so few genes being detected, considering the large number of genes present in the genome? (this one could use some work)

**Comment by jihe-liu** [comment]
I think the current questions (https://github.com/hbctraining/scRNA-seq_online/blob/master/homework/Day1_exercise.R) are good already. We just need to update these questions and answers in the answer key(https://github.com/hbctraining/scRNA-seq_online/blob/master/homework/Day1_exercise_answer_key.R).

**Comment by mistrm82** [comment]
@jihe-liu I found answer keys! 

https://github.com/hbctraining/scRNA-seq_online/blob/master/lessons/sc_exercises_qc_analysis.md

**Comment by mistrm82** [comment]
It was confusing because there are alo answer keys in markdown format located in the lessons folder. I left those there (since they are linked to in the main lesson). I created this : https://github.com/hbctraining/scRNA-seq_online/blob/master/homework/Day1_exercise_answer_key.md

which will be linked on main schedule page
