### ISSUE TITLE
update the workflow image

### ISSUE THREAD

**Issue by mistrm82** [hbctraining/scRNA-seq_online#56]
SCT and exploring unwanted variation is missing in the boxes

**Comment by rkhetani** [comment]
Recreated workflow images `Teaching/Flow_Diagrams_and_Figures/scRNA-Seq\ flowchart.key`

**Comment by rkhetani** [comment]
@mistrm82 can you check for the workflow and I will update the lessons accordingly.

**Comment by mistrm82** [comment]
added to all lessons
