### ISSUE TITLE
DefaultAssay for marker indentification

### ISSUE THREAD

**Issue by kpatel427** [hbctraining/scRNA-seq_online#58]
Hello,

Thank you for creating these lessons, they truly are a valuable resource to understanding single cell data processing. 
I have a question with regards to setting defaultAssay in lesson '09_merged_SC_marker_identification.md'.

Shouldn't the defaultAssay be set to `integrated` instead of `RNA`?

Since we integrated samples from two conditions, wouldn't we want to find conserved markers using integrated dataset? We have performed SCTransform on 3000 variable features (which are anchor features to integrate data), we do not have top variable features identified in our `RNA` assay. Wouldn't it throw an error while trying to use `FindConservedMarkers()` on `RNA` assay?

I will be happy to hear your thoughts on this.

Best,
Khushbu

**Comment by mistrm82** [comment]
Hi Khushbu,

When you run FindMarkers, or any flavor of this function you are performing a differential expression analysis. DE analysis should be run on the raw counts and using all genes for best results. The RNA slot contains the raw counts for all genes. Using the integrated slot not only give s you less genes but it is batch corrected values and so the assumptions of the statstical model for DE are not met.

There are many posts on this question, but here is a good one with helpful links: https://www.biostars.org/p/399789/
