### ISSUE TITLE
Reference for pseudobulk approach for DE analysis

### ISSUE THREAD

**Issue by marypiper** [hbctraining/scRNA-seq_online#68]
Hi All!

Couple things :)

- Nice reference for using pseudobulk method for DE analysis: https://www.nature.com/articles/s41467-021-25960-2.

- Also, DE pseudobulk lesson isn't linked in self-learning schedule

**Comment by rkhetani** [comment]
@marypiper Thanks for the paper - noted. And the DE pseudobulk lesson added to self-learning page. :)

**Comment by marypiper** [comment]
Awesome :)
