### ISSUE TITLE
new version of scTransform released!

### ISSUE THREAD

**Issue by pipes82** [hbctraining/scRNA-seq_online#78]
Hey All! Let me know if I am issuing too many issues - or better to post in Slack? Feel free to close if not interested in updating right now. I am currently testing it out so feel free to reach out too - supposed to be better memory/resource usage.

Vignette: https://satijalab.org/seurat/articles/sctransform_v2_vignette.html
Corresponding paper: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02584-9

I had to update all of the Seurat dependencies before installing:

```
remotes::install_github("mojaveazure/seurat-object")
devtools::install_github("satijalab/sctransform", ref = "develop")
devtools::install_github("satijalab/seurat", ref = "develop")
BiocManager::install("glmGamPoi")
```

Best,
Mary

**Comment by mistrm82** [comment]
Thanks @pipes82  :)  We'll probably address this closer to the next workshop.

Preference for GitHub issues, that way we remember to address it!

**Comment by mistrm82** [comment]
Check to see if we still need the dev branch

**Comment by mistrm82** [comment]
Don't need the dev branch, only need to make sure people have glmGamPoi installed (which is on our prep list anayways)
