### ISSUE TITLE
single_cell_rnaseq.zip no longer available on Dropbox

### ISSUE THREAD

**Issue by rbatorsky** [hbctraining/scRNA-seq_online#79]
Hello and thanks for the helpful workshop, I always use it to train students.
I thought I'd let you know that the file [single_cell_rnaseq.zip](https://www.dropbox.com/s/dl/we1gmyb9c8jej2u/single_cell_rnaseq.zip) linked on this [page](https://github.com/hbctraining/scRNA-seq_online/blob/master/schedule/links-to-lessons.md) is no longer available. 
As you point out, there are other ways of downloading the data, so we can still do the training.

**Comment by singhh5050** [comment]
Hi! I'm trying to learn sc-RNA analysis on my own through this lesson. How do you download the data contained in single_cell_rnaseq.zip?

**Comment by mistrm82** [comment]
Hi @rbatorsky and @singhh5050  we will update the link this week. Thanks for bringing it to our attention

**Comment by singhh5050** [comment]
Thank you so much!! :)
