### ISSUE TITLE
Decision tree?

### ISSUE THREAD

**Issue by eberdan** [hbctraining/scRNA-seq_online#90]
Might be good to start with a decision tree of when you want to use scRNA, bulk RNA, bulk sorted, insitu hybridization, etc

**Comment by rkhetani** [comment]
Instead of a decision tree, maybe we add a slide or a bullet point about this in the Intro slides. And also ask Mandovi/Arpita to highlight it.

**Comment by rkhetani** [comment]
Take some examples of scrnaseq vs bulk from Sarah B's slides for intro

**Comment by mistrm82** [comment]
This is covered in Arpita's slides
