### ISSUE TITLE
Normalization at various steps 

### ISSUE THREAD

**Issue by rkhetani** [hbctraining/scRNA-seq_online#97]
I am confused about this, but the idea is whether we are normalizing too much or too little.

**Comment by mistrm82** [comment]
We NormalizeData on the filtered+merged object, and presumably that gets stored in seurat@assays$RNA@data

Then before we look at FeaturePlots for each marker gene, we run NormalizeData again. We should look at values currently in data and then see how/if those values change when we run it again. My guess is that it will normalize the counts which are in seurat@assays$RNA@counts and replace what is in data. If so, this step is redundant and not necessary.

**Comment by mistrm82** [comment]
The functions NormalizeData, VariableFeatures and ScaleData can be replaced by the function SCTransform. The latter uses a more sophisticated way to perform the normalization and scaling, and is [argued to perform better](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1874-1). However, it is slower, and a bit less transparent compared to using the three separate functions.

We should update to SCT

**Comment by mistrm82** [comment]
Or we can add a note to justify why we use logNormalize - because  it is good to observe the data and any trends using a simple transformation and asses the need for anything else

**Comment by mistrm82** [comment]
added a note
