### ISSUE TITLE
obtaining raw data for the tutorial (lesson 03 SC quality control setup)

### ISSUE THREAD

**Issue by obalasz** [hbctraining/scRNA-seq_online#99]
Hi!
The tutorial (lesson 03) says the following:
This dataset is available on GEO ([GSE96583](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE96583)), however the available counts matrix lacked mitochondrial reads, so we downloaded the BAM files from the SRA ([SRP102802](https://www-ncbi-nlm-nih-gov.ezp-prod1.hul.harvard.edu/sra?term=SRP102802)). These BAM files were converted back to FASTQ files, then run through [Cell Ranger](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/what-is-cell-ranger) to obtain the count data that we will be using.

I downloaded the BAM files as well as the raw FASTQ files from the linked repository. Unfortunately, I wasn't able to run Cell Ranger on these files. Can you describe how you exactly reproduced the input for the Cell Ranger? Or can you suggest some alternative ways to obtain the input (such as `barcodes.tsv`, `features.tsv` etc.) for this tutorial? 

Thanks!

**Comment by rkhetani** [comment]
Hi @obalasz the data is available as a link on this page - https://hbctraining.github.io/scRNA-seq_online/schedule/links-to-lessons.html#installations. Please click on "Download this project" to follow along with the lessons.

If you want to re-create them using Cell Ranger let us know and we can dig up the scripts we use.
